spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/workspace/spring-cloud-config/config-server/configuration
  application:
    name: config-server
server:
  port: 8888
